# -*- mode: ruby -*-
# # vi: set ft=ruby :

#
# NOTE: This has been tested with a very specific set of tools. Please
#       see this bug for more info: https://github.com/hashicorp/vagrant/issues/11849
#

#
# NOTE: If port collission errors happen with Vagrant vmware_desktop
#       provider, try running the following in order:
#
#       0. Ensure VMware Desktop/Fusion is closed
#       1. make local-cluster-implode
#       2. rm -rf .local-cluster/.vagrant
#       3. Remove the corresponding port entry in /Library/Preferences/VMWare\ Fusion/networking
#       4. Remove the corresponding port entry in /Library/Preferences/VMWare\ Fusion/vmnet8/nat.conf
#       5. sudo rm -f /opt/vagrant-vmware-desktop/settings/nat.json
#       6. sudo killall vagrant-vmware-utility
#       7. make local-cluster
#
#       Reference: https://www.cryptica.me/blog/port-forward-collision/

Vagrant.require_version ">= 2.2.9"

Vagrant.configure(2) do |config|
  #
  # Common configuration
  #
  config.ssh.username = 'ubuntu'
  config.ssh.password = 'ubuntu'
  config.ssh.insert_key = true
  config.vm.box = 'local-cluster'
  config.vm.box_url = 'file://../.tmp/output/local-cluster.box'
  # If you would rather not build your own box, uncomment the following.
  # Note that it's not guaranteed to be synced to the code in builder/
  # See https://app.vagrantup.com/mmaglana/boxes/gitlab
  # config.vm.box = 'mmaglana/gitlab'

  # We don't need shared folders for the local cluster
  config.vm.synced_folder '.', '/vagrant', disabled: true

  #
  # GitLab
  #
  config.vm.define 'gitlab' do |gitlab|
    gitlab.vm.network 'private_network', ip: ENV['local_gitlab_ip']

    gitlab.vm.provider :vmware_desktop do |v|
      v.gui    = false
      v.cpus   = 2
      v.memory = 4096
    end
  end

  #
  # GitLab Runner
  #
  config.vm.define 'runner' do |runner|
    runner.vm.network 'private_network', ip: ENV['local_runner_ip']

    runner.vm.provider :vmware_desktop do |v|
      v.gui    = false
      v.cpus   = 2
      v.memory = 4096
    end
  end
end
