# -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant.require_version ">= 2.2.9"

Vagrant.configure(2) do |config|
  #
  # Common configuration
  #
  config.ssh.username = 'ubuntu'
  config.ssh.password = 'ubuntu'
  config.ssh.insert_key = false
  config.vm.box = 'local-cluster'
  config.vm.box_url = 'file://../.tmp/output/local-cluster.box'
  # We don't need this and it certainly doesn't work
  config.vm.synced_folder '.', '/vagrant', disabled: true

  #
  # GitLab
  #
  config.vm.define 'gitlab' do |gitlab|
    gitlab.vm.network 'private_network', ip: '192.168.246.10'

    gitlab.vm.provider :virtualbox do |vbox|
      vbox.gui    = false
      vbox.cpus   = 2
      vbox.memory = 2048
    end
  end

  #
  # GitLab Runner
  #
  config.vm.define 'runner' do |runner|
    runner.vm.network 'private_network', ip: '192.168.246.11'

    runner.vm.provider :virtualbox do |vbox|
      vbox.gui    = false
      vbox.cpus   = 2
      vbox.memory = 2048
    end
  end
end
