#!/usr/bin/env bash -e
[ ! -f ${configdir}/vars.yml ] && \
    echo "ERROR: ${configdir}/vars.yml does not exist!" && \
    exit 1

export local_gitlab_fqdn=$(grep "gitlab_fqdn:" "${configdir}/vars.yml" | sed "s/gitlab_fqdn: *//g")

export local_gitlab_ip='192.168.246.10'
export local_runner_ip='192.168.246.11'

export local_cluster_ssh_config_marker_start="# === CICD_LOCAL_CLUSTER_SSH_CONFIG_BEGIN ==="
export local_cluster_ssh_config_marker_end="# === CICD_LOCAL_CLUSTER_SSH_CONFIG_END ==="

export local_cluster_etc_hosts_marker_start="# === CICD_LOCAL_CLUSTER_HOSTS_BEGIN ==="
export local_cluster_etc_hosts_marker_end="# ===  CICD_LOCAL_CLUSTER_HOSTS_END  ==="
