#!/usr/bin/env bash -e
# NOTE: Any echos made here will not be displayed on the terminal since
# it will be captured by the parent process. If you want to check for
# the presence of $1, do the check in the parent process.
cluster_id="$1"
vault_passwords_dir=$HOME/.relaxdiego/cicd/vault-passwords
echo -n "${vault_passwords_dir}/${cluster_id}"
