#!/usr/bin/env bash -e
cd $configdir
source lib/environment
vagrant destroy -f

echo "Removing ~/.ssh/config custom entries"
sed -i "/$local_cluster_ssh_config_marker_start/,/$local_cluster_ssh_config_marker_end/ d" ~/.ssh/config
rm -f "${cluster_created_flag}"
